apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: the-app-hub
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/HassanHI3/advanced-k8-labs.git  # <-- swap this
    targetRevision: main
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: the-app-hub
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true